---
- name: ansible-role-ostack-component-installer | install prereq for redhat
  include: redhat.yaml

- name: add hashicorp repo
  yum_repository:
      name: hashicorp
      description: hashicorp consul etc
      baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: add tools repo
  yum_repository:
      name: tools
      description: tools needed in ostack
      baseurl: http://{{ toolserver }}/tools.repo

- name:  install consul
  ansible.builtin.package:
    name: consul
    state: present