---
- name: ansible-role-ostack-component-installer | install prereq for redhat
  include: redhat.yaml

- name: add hashicorp repo
  yum_repository:
      name: hashicorp
      description: hashicorp consul etc
      baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: add pip2scl repo
  yum_repository:
      name: pip2scl
      description: scl enables rpms
      baseurl: http://repos.pip2scl.dk/pip2scl.repo

- name:  install consul
  ansible.builtin.package:
    name: consul
    state: present